/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barbearia.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblDataNome = new javax.swing.JLabel();
        lblUsuarioNome = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menucadastro = new javax.swing.JMenu();
        cadastrocliente = new javax.swing.JMenuItem();
        cadastrousuario = new javax.swing.JMenuItem();
        cadastrorecepcao = new javax.swing.JMenuItem();
        menuagendar = new javax.swing.JMenu();
        agendaservico = new javax.swing.JMenuItem();
        agendacorte = new javax.swing.JMenuItem();
        menuvenda = new javax.swing.JMenu();
        vendaprodutos = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        menusobre = new javax.swing.JMenuItem();
        menuopcoes = new javax.swing.JMenu();
        opcoessair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\victo\\Downloads\\NetBeans\\Icones\\Barbearia Logo 3.png")); // NOI18N

        lbldata.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        lbldata.setText("Data");

        lblusuario.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusuario.setText("Usuário");

        lblDataNome.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        lblDataNome.setText("Data:");

        lblUsuarioNome.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        lblUsuarioNome.setText("Usuário:");

        menucadastro.setText("Cadastro");
        menucadastro.setEnabled(false);
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });

        cadastrocliente.setText("Cliente");
        cadastrocliente.setEnabled(false);
        cadastrocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroclienteActionPerformed(evt);
            }
        });
        menucadastro.add(cadastrocliente);

        cadastrousuario.setText("Usuário");
        cadastrousuario.setEnabled(false);
        cadastrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrousuarioActionPerformed(evt);
            }
        });
        menucadastro.add(cadastrousuario);

        cadastrorecepcao.setText("Recepção");
        cadastrorecepcao.setEnabled(false);
        cadastrorecepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrorecepcaoActionPerformed(evt);
            }
        });
        menucadastro.add(cadastrorecepcao);

        menu.add(menucadastro);

        menuagendar.setText("Agendamento");

        agendaservico.setText("Serviço");
        agendaservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaservicoActionPerformed(evt);
            }
        });
        menuagendar.add(agendaservico);

        agendacorte.setText("Agendar Corte");
        agendacorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendacorteActionPerformed(evt);
            }
        });
        menuagendar.add(agendacorte);

        menu.add(menuagendar);

        menuvenda.setText("Venda");
        menuvenda.setEnabled(false);

        vendaprodutos.setText("Produtos");
        vendaprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaprodutosActionPerformed(evt);
            }
        });
        menuvenda.add(vendaprodutos);

        menu.add(menuvenda);

        MenuAjuda.setText("Ajuda");
        MenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaActionPerformed(evt);
            }
        });

        menusobre.setText("Sobre");
        menusobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(menusobre);

        menu.add(MenuAjuda);

        menuopcoes.setText("Opções");

        opcoessair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        opcoessair.setText("Sair");
        opcoessair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoessairActionPerformed(evt);
            }
        });
        menuopcoes.add(opcoessair);

        menu.add(menuopcoes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDataNome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioNome)
                .addGap(9, 9, 9)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Principal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vendaprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaprodutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendaprodutosActionPerformed

    private void cadastrorecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrorecepcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrorecepcaoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // substitui a label lbldata para a data atual do sistema
        Date data = new Date();
        DateFormat formatadata = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldata.setText(formatadata.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void opcoessairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoessairActionPerformed
        // configuração do atalho sair (alt + f4)
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_opcoessairActionPerformed

    private void MenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaActionPerformed
        
    }//GEN-LAST:event_MenuAjudaActionPerformed

    private void menusobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusobreActionPerformed
        // chamada do evento sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_menusobreActionPerformed

    private void cadastroclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroclienteActionPerformed
        // Cadastro de Clientes/Usuários
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_cadastroclienteActionPerformed

    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed

    private void cadastrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrousuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuario usu = new TelaUsuario();
        usu.setVisible(true);
        desktop.add(usu);
    }//GEN-LAST:event_cadastrousuarioActionPerformed

    private void agendaservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaservicoActionPerformed
        // Chama a TelaServicos
        TelaServicos servico = new TelaServicos();
        servico.setVisible(true);
        desktop.add(servico);
    }//GEN-LAST:event_agendaservicoActionPerformed

    private void agendacorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendacorteActionPerformed
        // Chama a TelaAgendamento
        TelaAgendamento agendamento = new TelaAgendamento();
        agendamento.setVisible(true);
        desktop.add(agendamento);
    }//GEN-LAST:event_agendacorteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuItem agendacorte;
    private javax.swing.JMenuItem agendaservico;
    public static javax.swing.JMenuItem cadastrocliente;
    public static javax.swing.JMenuItem cadastrorecepcao;
    public static javax.swing.JMenuItem cadastrousuario;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDataNome;
    public static javax.swing.JLabel lblUsuarioNome;
    private javax.swing.JLabel lbldata;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuagendar;
    public static javax.swing.JMenu menucadastro;
    private javax.swing.JMenu menuopcoes;
    private javax.swing.JMenuItem menusobre;
    public static javax.swing.JMenu menuvenda;
    private javax.swing.JMenuItem opcoessair;
    private javax.swing.JMenuItem vendaprodutos;
    // End of variables declaration//GEN-END:variables
}
