/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package barbearia.telas;

import barbearia.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author victo
 */
public class TelaClienteVenda extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form TelaClienteVenda
     */
    public TelaClienteVenda() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    //Filtro de pesquisa para produtos
        private void pesquisarproduto(){
        String sql = "select idproduto as Id, nomeproduto as Nome, quantidade as Quantidade, valor as Valor from produto where nomeproduto like ?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtCliVendaProdPesquisa.getText() + '%');
                rs=pst.executeQuery();
                tblCliVendaProd.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
        }  
    }
        
    //Set campos
        private void set_campos(){
            int setar = tblCliVendaProd.getSelectedRow();
            txtCliVendaProdId.setText(tblCliVendaProd.getModel().getValueAt(setar,0).toString());
            txtCliVendaProdNome.setText(tblCliVendaProd.getModel().getValueAt(setar,1).toString());
            txtCliVendaProdQtde.setText(tblCliVendaProd.getModel().getValueAt(setar,2).toString());
            txtCliVendaProdValor.setText(tblCliVendaProd.getModel().getValueAt(setar,3).toString());
        }
        
        //Calcula o valor do produto
        private void calculaValorTotal() {
        try {
            //Faz a multiplicação quantidadedesejada * valor do produto
            int quantidade = Integer.parseInt(txtCliVendaProdQtdeDesejada.getText());
            float valorProduto = Float.parseFloat(txtCliVendaProdValor.getText());
            float valorTotal = quantidade * valorProduto;
            
            //Mostra o resultado do cálculo
            txtCliVendaProdValTotal.setText(String.format("%.2f", valorTotal));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, insira uma quantidade válida.");
        }
    }
        
        private void comprar(){
            int confirmar = JOptionPane.showConfirmDialog(null, "Deseja confirmar a compra?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (confirmar == JOptionPane.YES_OPTION){
            String sql = "update produto set quantidade = quantidade - ? where idproduto = ? ";
                try {
                    int quantidadeDesejada = Integer.parseInt(txtCliVendaProdQtdeDesejada.getText());
                    int idProduto = Integer.parseInt(txtCliVendaProdId.getText());
            
                    // Prepara a declaração SQL
                    pst = conexao.prepareStatement(sql);
                    pst.setInt(1, quantidadeDesejada);
                    pst.setInt(2, idProduto);
                    
                    int adicionado = pst.executeUpdate();
                    if (adicionado > 0) {
                        JOptionPane.showMessageDialog(null, "Compra realizado com sucesso!");
                        txtCliVendaProdQtdeDesejada.setText(null);
                        txtCliVendaProdValTotal.setText(null);
                } else {
                JOptionPane.showMessageDialog(null, "Não foi possível realizar a compra.");
            }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro ao realizar a compra, tente novamente");
                }
            }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telausuarioid = new javax.swing.JLabel();
        btnCliVendaProdCompra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliVendaProd = new javax.swing.JTable();
        txtCliVendaProdPesquisa = new javax.swing.JTextField();
        txtCliVendaProdId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        telausuarionome = new javax.swing.JLabel();
        txtCliVendaProdNome = new javax.swing.JTextField();
        telausuarionome2 = new javax.swing.JLabel();
        txtCliVendaProdValor = new javax.swing.JTextField();
        txtCliVendaProdQtdeDesejada = new javax.swing.JTextField();
        telausuarionome3 = new javax.swing.JLabel();
        telausuarionome4 = new javax.swing.JLabel();
        txtCliVendaProdQtde = new javax.swing.JTextField();
        telausuarionome5 = new javax.swing.JLabel();
        txtCliVendaProdValTotal = new javax.swing.JTextField();
        btnCliVendaProdCalcular = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(837, 509));

        telausuarioid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarioid.setText("Id:");

        btnCliVendaProdCompra.setText("Comprar");
        btnCliVendaProdCompra.setToolTipText("Alterar");
        btnCliVendaProdCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliVendaProdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliVendaProdCompraActionPerformed(evt);
            }
        });

        tblCliVendaProd = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblCliVendaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdProduto", "Nome", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliVendaProd.getTableHeader().setResizingAllowed(false);
        tblCliVendaProd.getTableHeader().setReorderingAllowed(false);
        tblCliVendaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCliVendaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliVendaProd);

        txtCliVendaProdPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCliVendaProdPesquisaKeyReleased(evt);
            }
        });

        txtCliVendaProdId.setBackground(new java.awt.Color(60, 63, 65));
        txtCliVendaProdId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdId.setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\victo\\Downloads\\NetBeans\\Icones\\icone pesquisar.png")); // NOI18N
        jLabel1.setText("jLabel1");

        telausuarionome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarionome.setText("Nome:");

        txtCliVendaProdNome.setEditable(false);
        txtCliVendaProdNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliVendaProdNomeActionPerformed(evt);
            }
        });

        telausuarionome2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarionome2.setText("Valor:");

        txtCliVendaProdValor.setEditable(false);
        txtCliVendaProdValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliVendaProdValorActionPerformed(evt);
            }
        });

        txtCliVendaProdQtdeDesejada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdQtdeDesejada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliVendaProdQtdeDesejadaActionPerformed(evt);
            }
        });

        telausuarionome3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarionome3.setText("Quantidade desejada:");

        telausuarionome4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarionome4.setText("Quantidade disponível:");

        txtCliVendaProdQtde.setEditable(false);
        txtCliVendaProdQtde.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliVendaProdQtdeActionPerformed(evt);
            }
        });

        telausuarionome5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telausuarionome5.setText("Valor Total:");

        txtCliVendaProdValTotal.setEditable(false);
        txtCliVendaProdValTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliVendaProdValTotal.setFocusable(false);

        btnCliVendaProdCalcular.setText("Calcular preço");
        btnCliVendaProdCalcular.setToolTipText("Alterar");
        btnCliVendaProdCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliVendaProdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliVendaProdCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCliVendaProdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(telausuarioid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCliVendaProdId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telausuarionome5)
                            .addComponent(telausuarionome3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliVendaProdQtdeDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliVendaProdValTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCliVendaProdCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliVendaProdCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(360, 360, 360))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telausuarionome)
                            .addComponent(telausuarionome2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliVendaProdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtCliVendaProdValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telausuarionome4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCliVendaProdQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliVendaProdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliVendaProdId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telausuarioid))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliVendaProdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telausuarionome)
                    .addComponent(telausuarionome4)
                    .addComponent(txtCliVendaProdQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliVendaProdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telausuarionome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telausuarionome3)
                    .addComponent(txtCliVendaProdQtdeDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliVendaProdCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliVendaProdCompra)
                    .addComponent(txtCliVendaProdValTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telausuarionome5))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCliVendaProdPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCliVendaProdPesquisaKeyReleased
        // pesquisarproduto
        pesquisarproduto();
    }//GEN-LAST:event_txtCliVendaProdPesquisaKeyReleased

    private void btnCliVendaProdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliVendaProdCompraActionPerformed
        // Comprar produtos
        comprar();

    }//GEN-LAST:event_btnCliVendaProdCompraActionPerformed

    private void tblCliVendaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCliVendaProdMouseClicked
        // Setar produtos
        set_campos();
    }//GEN-LAST:event_tblCliVendaProdMouseClicked

    private void txtCliVendaProdValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliVendaProdValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliVendaProdValorActionPerformed

    private void txtCliVendaProdQtdeDesejadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliVendaProdQtdeDesejadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliVendaProdQtdeDesejadaActionPerformed

    private void txtCliVendaProdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliVendaProdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliVendaProdNomeActionPerformed

    private void txtCliVendaProdQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliVendaProdQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliVendaProdQtdeActionPerformed

    private void btnCliVendaProdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliVendaProdCalcularActionPerformed
        // Calcula o valor do preço de acordo com a qtde
        calculaValorTotal();
    }//GEN-LAST:event_btnCliVendaProdCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliVendaProdCalcular;
    private javax.swing.JButton btnCliVendaProdCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliVendaProd;
    private javax.swing.JLabel telausuarioid;
    private javax.swing.JLabel telausuarionome;
    private javax.swing.JLabel telausuarionome2;
    private javax.swing.JLabel telausuarionome3;
    private javax.swing.JLabel telausuarionome4;
    private javax.swing.JLabel telausuarionome5;
    private javax.swing.JTextField txtCliVendaProdId;
    private javax.swing.JTextField txtCliVendaProdNome;
    private javax.swing.JTextField txtCliVendaProdPesquisa;
    private javax.swing.JTextField txtCliVendaProdQtde;
    private javax.swing.JTextField txtCliVendaProdQtdeDesejada;
    private javax.swing.JTextField txtCliVendaProdValTotal;
    private javax.swing.JTextField txtCliVendaProdValor;
    // End of variables declaration//GEN-END:variables
}
