/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package barbearia.telas;

import barbearia.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author victo
 */
public class TelaAgendamento extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    private String tipo;
    
    /**
     * Creates new form TelaAgendamento
     */
    public TelaAgendamento() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    private void pesquisarClienteAgendamento(){
        String sql = "select idcliente as Id, nome as Nome, telefone as Telefone from cliente where nome like ?";   
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtServicoPesquisar.getText() + "%");
            rs=pst.executeQuery();
            tblAgendamentos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setCampos(){
        int setar = tblAgendamentos.getSelectedRow();
        txtTelaAgendamentoId.setText(tblAgendamentos.getModel().getValueAt(setar, 0).toString());
    }
    
    //Cadastrar agendamento
    private void cadastrar_agendamento(){
        String sql = "insert into agendamento(tipo_servico, data_agendamento, hora_agendamento, clienteid) values(?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            // Implementação da data
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String data = sdf.format(TelaAgendamentoData.getDate());
            pst.setString(1, tipo);
            //rs=pst.executeQuery();
            pst.setString(2, data);    
            pst.setString(3, cboxHoraAgendamento.getSelectedItem().toString());
            pst.setString(4, txtTelaAgendamentoId.getText());
            
            //Validação dos campos
            if (tipo.isEmpty() || TelaAgendamentoData == null || txtTelaAgendamentoId.getText().isEmpty() || cboxHoraAgendamento.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios");
            } else {
                    int adicionado =pst.executeUpdate();
                    if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Agendamento realizado com sucesso!");
                    txtTelaAgendamentoId.setText(null);
                    TelaAgendamentoData.setDate(null);
                    cboxHoraAgendamento.setSelectedItem(null);
                }
            }      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblagendamentoescolha = new javax.swing.JLabel();
        rbttncabelo = new javax.swing.JRadioButton();
        rbttnbarba = new javax.swing.JRadioButton();
        rbttncombo = new javax.swing.JRadioButton();
        lblagendamentodata = new javax.swing.JLabel();
        lblagendamentohorario = new javax.swing.JLabel();
        TelaAgendamentoData = new com.toedter.calendar.JDateChooser();
        cboxHoraAgendamento = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtTelaAgendamentoId = new javax.swing.JTextField();
        lblagendamentoescolha1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        txtServicoPesquisar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agendamento");
        setPreferredSize(new java.awt.Dimension(837, 509));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agendamento"));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblagendamentoescolha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblagendamentoescolha.setText("Escolha o serviço desejado:");

        rbttncabelo.setText("Cabelo");
        rbttncabelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttncabeloActionPerformed(evt);
            }
        });

        rbttnbarba.setText("Barba");
        rbttnbarba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttnbarbaActionPerformed(evt);
            }
        });

        rbttncombo.setText("Combo");
        rbttncombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttncomboActionPerformed(evt);
            }
        });

        lblagendamentodata.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblagendamentodata.setText("Escolha a data:");

        lblagendamentohorario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblagendamentohorario.setText("Escolha o horário:");

        cboxHoraAgendamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:30", "14:00", "15:00", "15:30", "16:00", "16:30" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        txtTelaAgendamentoId.setBackground(new java.awt.Color(60, 63, 65));
        txtTelaAgendamentoId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelaAgendamentoId.setEnabled(false);

        lblagendamentoescolha1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblagendamentoescolha1.setText("Id:");

        tblAgendamentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgendamentos.getTableHeader().setResizingAllowed(false);
        tblAgendamentos.getTableHeader().setReorderingAllowed(false);
        tblAgendamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgendamentos);

        txtServicoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServicoPesquisarKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServicoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblagendamentoescolha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelaAgendamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelaAgendamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblagendamentoescolha1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblagendamentoescolha)
                    .addComponent(jButton1)
                    .addComponent(TelaAgendamentoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblagendamentohorario)
                    .addComponent(cboxHoraAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbttncabelo)
                    .addComponent(rbttnbarba)
                    .addComponent(rbttncombo)
                    .addComponent(lblagendamentodata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblagendamentoescolha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbttncabelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbttnbarba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbttncombo)
                        .addGap(18, 18, 18)
                        .addComponent(lblagendamentodata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelaAgendamentoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblagendamentohorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxHoraAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Confirmar Agendamento
        cadastrar_agendamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbttncabeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttncabeloActionPerformed
        // Atribuição de texto ao ser selecionado
        tipo = "Cabelo";
    }//GEN-LAST:event_rbttncabeloActionPerformed

    private void rbttnbarbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttnbarbaActionPerformed
        // Atribuição de texto ao ser selecionado
        tipo = "Barba";
    }//GEN-LAST:event_rbttnbarbaActionPerformed

    private void rbttncomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttncomboActionPerformed
        // Atribuição de texto ao ser selecionado
        tipo = "Combo";
    }//GEN-LAST:event_rbttncomboActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtServicoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServicoPesquisarKeyReleased
        // Chamando PesquisarCliente
        pesquisarClienteAgendamento();
    }//GEN-LAST:event_txtServicoPesquisarKeyReleased

    private void tblAgendamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendamentosMouseClicked
        // Setar Clientes
        setCampos();
    }//GEN-LAST:event_tblAgendamentosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TelaAgendamentoData;
    private javax.swing.JComboBox<String> cboxHoraAgendamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblagendamentodata;
    private javax.swing.JLabel lblagendamentoescolha;
    private javax.swing.JLabel lblagendamentoescolha1;
    private javax.swing.JLabel lblagendamentohorario;
    private javax.swing.JRadioButton rbttnbarba;
    private javax.swing.JRadioButton rbttncabelo;
    private javax.swing.JRadioButton rbttncombo;
    private javax.swing.JTable tblAgendamentos;
    private javax.swing.JTextField txtServicoPesquisar;
    private javax.swing.JTextField txtTelaAgendamentoId;
    // End of variables declaration//GEN-END:variables
}
